### ISSUE TITLE
Move metadata writes to be atomic with datastore writes + improve performance

### ISSUE THREAD

**Issue by mikejohnstn** [Simperium/simperium-ios#124]
Currently there is still metadata stored in NSUserDefaults (e.g. for pending changes). It's possible, if an app crashes, that this could fall out of sync with objects that have been written to the datstore.

Ideally, data writes and associated metadata should be written atomically. This will probably involve dynamically creating an entity in the persistent store for all Simperium metadata instead of using NSUserDefaults or Core Data UserInfo.

**Comment by jleandroperez** [comment]
Closing in favor of Issue #442
