### ISSUE TITLE
Relationships Must Be Marked As Optional

### ISSUE THREAD

**Issue by alekseyn** [Simperium/simperium-ios#14]
In order for Simperium to correct sync an object graph, relationships must always be marked as optional. This appears to be a requirement since entity data may arrive at the client in an undefined sequence. However, the client's own validation logic may require certain relationships to be properly indicated as mandatory.

It would be helpful for relationships to be defined as either optional or mandatory, as required by a specific application, and for simperium to sync correctly, regardless of whether or not relationships are marked as optional.

**Comment by jleandroperez** [comment]
Closing in favor of Issue #442
