### ISSUE TITLE
Complete implementation of SPUser's 'customObject' stub methods

### ISSUE THREAD

**Issue by converted2mac** [Simperium/simperium-ios#149]
Issue to track the progress of the methods which currently sit in the SPUser class. Excited to be able to attach some custom user info to the actual user account, rather than trying to implement something that syncs as a core data object.
```Objective-C
-(void)setCustomObject:(id)object forKey:(NSString *)key;
-(id)getCustomObjectForKey:(NSString *)key;

**Comment by jleandroperez** [comment]
Closing in favor of Issue #442
