### ISSUE TITLE
Simperium Error [Client Error : 404] while processing changes for object

### ISSUE THREAD

**Issue by lukegeiger** [Simperium/simperium-ios#402]
@jleandroperez  Getting This Error when deleting a variety of objects that are all related to each other. The data seems to be deleting both locally and on simperium... Not sure if it is something to worry about or not. Let me know if you need logs. Replicates maybe 5/10 times.

**Comment by jleandroperez** [comment]
@lukegeiger sorry to bother you! have you been experiencing this issue with the latest builds? (if so, the logs would be super helpful!).

Thanks!

**Comment by jleandroperez** [comment]
Closing this one as cannot repro. If needed, please, reopen with console logs.

Thank you!
