### ISSUE TITLE
Crash during signOutAndRemoveLocalData:YES

### ISSUE THREAD

**Issue by CapoChino** [Simperium/simperium-ios#424]
Hi,

I'm dusting off my Simperium integration in hopes that the bug I was hitting a fews months ago (#250) has been fixed.  I'm using the develop branch.  (Should I use master instead?)

I called signOutAndRemoveLocalData as follows:

[theSimperium signOutAndRemoveLocalData:YES completion:^{
				NSLog(@"Finished logging out.");
				isSigningOut = NO;
				[self updateInterface];
			}];

It's worked fine several times, but just now it crashed.  I don't know if it will reproduce.  Following is the trace.  Let me know if there's anything else you need.

Thank you!

Cheers,
Casey

* thread #1: tid = 0x4232a0, 0x000000010bd35017 libobjc.A.dylib`objc_msgSend + 23, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
    frame #0: 0x000000010bd35017 libobjc.A.dylib`objc_msgSend + 23
    frame #1: 0x00000001097428bd CoreData`__77-[NSFetchedResultsController(PrivateMethods) _managedObjectContextDidChange:]_block_invoke + 2045
    frame #2: 0x0000000109673f06 CoreData`developerSubmittedBlockToNSManagedObjectContextPerform + 198
    frame #3: 0x0000000109673de1 CoreData`-[NSManagedObjectContext performBlockAndWait:] + 241
    frame #4: 0x00000001097420a7 CoreData`-[NSFetchedResultsController(PrivateMethods) _managedObjectContextDidChange:] + 119
    frame #5: 0x000000010c671cec CoreFoundation`__CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
    frame #6: 0x000000010c5718a4 CoreFoundation`_CFXNotificationPost + 2484
    frame #7: 0x000000010aeb06b8 Foundation`-[NSNotificationCenter postNotificationName:object:userInfo:] + 66
    frame #8: 0x0000000109659c96 CoreData`-[NSManagedObjectContext(_NSInternalNotificationHandling) _postObjectsDidChangeNotificationWithUserInfo:] + 70
    frame #9: 0x00000001096e2d1e CoreData`-[NSManagedObjectContext(_NSInternalChangeProcessing) _createAndPostChangeNotification:withDeletions:withUpdates:withRefreshes:] + 334
    frame #10: 0x00000001096553d1 CoreData`-[NSManagedObjectContext(_NSInternalChangeProcessing) _processRecentChanges:] + 2897
    frame #11: 0x00000001096588f3 CoreData`-[NSManagedObjectContext save:] + 131
  * frame #12: 0x00000001085a4686 MyApp`-[SPCoreDataStorage deleteAllObjectsForBucketName:](self=0x00007ff862107020, _cmd=0x00000001087a7ca3, bucketName=0x00007ff860dfa420) + 1078 at SPCoreDataStorage.m:315
    frame #13: 0x00000001085d5061 MyApp`-[SPBucket deleteAllObjects](self=0x00007ff862410c00, _cmd=0x00000001087a2556) + 113 at SPBucket.m:116
    frame #14: 0x000000010c5ebe80 CoreFoundation`-[NSArray makeObjectsPerformSelector:] + 224
    frame #15: 0x0000000108579891 MyApp`-[Simperium _finishSignout:completion:](self=0x00007ff860fddcf0, _cmd=0x00000001087a253b, remove=true, completion=0x00007ff862623ee0) + 449 at Simperium.m:610
    frame #16: 0x00000001085795eb MyApp`__50-[Simperium signOutAndRemoveLocalData:completion:]_block_invoke370(.block_descriptor=<unavailable>) + 59 at Simperium.m:600
    frame #17: 0x000000010c049ba6 libdispatch.dylib`_dispatch_call_block_and_release + 12
    frame #18: 0x000000010c0677f4 libdispatch.dylib`_dispatch_client_callout + 8
    frame #19: 0x000000010c0508fb libdispatch.dylib`_dispatch_main_queue_callback_4CF + 949
    frame #20: 0x000000010c609fe9 CoreFoundation`__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
    frame #21: 0x000000010c5cceeb CoreFoundation`__CFRunLoopRun + 2043
    frame #22: 0x000000010c5cc486 CoreFoundation`CFRunLoopRunSpecific + 470
    frame #23: 0x000000010e6959f0 GraphicsServices`GSEventRunModal + 161
    frame #24: 0x0000000109bfb420 UIKit`UIApplicationMain + 1282
    frame #25: 0x0000000108496d77 MyApp`main(argc=1, argv=0x00007fff5776a318) + 71 at main.m:14
    frame #26: 0x000000010c09c145 libdyld.dylib`start + 1

**Comment by jleandroperez** [comment]
@CapoChino Sorry about the late reply on this one!. I've been unable to repro this crash.

From what you mention, it sounds highly likely that there was a memory leak somehow, and the FRC was getting a notification, when there should have never been a FRC active.

If anything, please, let us know.

Thank you!
