### ISSUE TITLE
fetchBatchSize ignored with Simperium setup

### ISSUE THREAD

**Issue by jphribovsek** [Simperium/simperium-ios#425]
I am not sure yet why this is happening, but when using a NSFetchedResultsController, which request has a custom fetchBatchSize, that batch size is ignored during fetching. The SQL logging shows the SELECT request grabs all objects.
This behavior is observed when setting up a simple project with SImperium.
A similar Core data project, without Simperium, doesn't exhibit the same behavior, the fetchBatchSize is reflected in the SQL query.

This causes major performance issues for large collections or collections of large objects

**Comment by jleandroperez** [comment]
I'm closing this issue since it's a Core Data bug. (Sorry about that JP!).
