### ISSUE TITLE
Podspec: Include SSKeychain as a dependency, rather than including the source

### ISSUE THREAD

**Issue by danielr** [Simperium/simperium-ios#452]
I've just run into a duplicate symbols issue after adding `SSKeychain` to my project (which also uses Simperium) and then I noticed that you include an (unprefixed!) version of this library in your source... Having a look at your Podfile, you seem to include most of your external stuff as Cocoapods dependencies (most notably JRSwizzle and SocketRocket) - why not do the same for SSKeychain?

But apart from that, if you also distribute your lib outside of Cocoapods, you should really think about prefixing your external dependencies (or remove them and require users to manually install them).

**Comment by jleandroperez** [comment]
@danielr you're indeed right sir. We'll be soon updating the way we handle dependencies.

Thanks for the suggestion!

**Comment by jleandroperez** [comment]
@danielr Dependencies prefixed, except for **DiffMatchPatch**, which will remain pristine, for the time being.

We'll be releasing a new Cocoapods version shortly, thank you!
