### ISSUE TITLE
Simperium Error [Client Error : 412] while processing changes for object

### ISSUE THREAD

**Issue by lukegeiger** [Simperium/simperium-ios#454]
I am trying to set a relationship like so

        for (Player*player in allPlayersInGame) {
        PlayerStats*playerStats = [NSEntityDescription insertNewObjectForEntityForName:@"PlayerStats" inManagedObjectContext:player.managedObjectContext];
        [player addRelationshipPlayerStatsObject:playerStats];
    }

I am getting the following error
    Simperium Error [Client Error : 412] while processing changes for object [Player]    [1dbf75950ffc4c31a56b8cef88486c06]

The relationship is saved correctly on simperium.com so why am I seeing this error?

**Comment by jleandroperez** [comment]
Error 412 means that the diff for that entity resulted in zero changes.

- Is the relationship marked as Optional?
- Assuming that the players are already inserted (and this loop only updates the relationship), if [you set a breakpoint here](https://github.com/Simperium/simperium-ios/blob/develop/Simperium/Simperium.m#L461) and hit `po [updatedObject simperiumValueForKey:@"playerStats"]`, is the *PlayerStats* entity being returned?.
- Would it be possible to grab the verbose logs?.

Thank you!

**Comment by jleandroperez** [comment]
@lukegeiger may i ask you if you've been able to retrieve the logs?. 

Thank you!

**Comment by lukegeiger** [comment]
@jleandroperez my fault for late response on this one. I haven't been able to get this to happen again. It happens every now and then though and next time I see it I will make sure to get the logs and possibly re open the issue.

**Comment by jleandroperez** [comment]
Thanks for the feedback Luke, closing for now. (If needed) please feel free to reopen.
Thank you!
