### ISSUE TITLE
Simperium not mapping NSValueTransformer correctly upon logging back in.

### ISSUE THREAD

**Issue by lukegeiger** [Simperium/simperium-ios#455]
@jleandroperez  As a workaround for Simperium not supporting many to many relationships I set up a NSValueTransformer on one of my classes that hold an array of Simperium keys that the object is related to. So, as an example my use case is as follows.

**Lineup**  has many **Players**
**Players** are apart of many **Lineups**

On my **Lineup** entity I have a *playerIDs*  id property that gets transformed into an NSArray
On my **Player** entity I have a *lineupIDs*  id property that gets transformed into an NSArray

Everything works fine with Simperium until I log out of the application and re log back in. When that happens, the *playerIDs* property on my **Lineup** are no longer there  and the *lineupIDs* are no longer on my **Player** are also no longer there.

The **Lineup** object returns nil for *playerIdDs* so the object looks like this

##### What the object looks like after logging back in.
    <Lineup: 0x170103f00> (entity: Lineup; id: 0xd000000000040004 <x-coredata://550A4D12-E78C-4D02-9110-EF0CE7BBB8C2/Lineup/p1> ; data: {
    ghostData = "{\n  \"key\" : \"c7537de8e1794863b9289ca52eec6743\",\n  \"version\" : \"1\",\n  \"obj\" : {\n    \"playerIDs\" : \"\",\n    \"relationshipTeam\" : \"2e5a3e1d168a4a77ac97aa3914ebaa1a\"\n  }\n}";
    playerIDs = nil;
    lineupStats =     (
        "0xd000000000080006 <x-coredata://550A4D12-E78C-4D02-9110-EF0CE7BBB8C2/LineupStats/p2>"
    );
    team = "0xd00000000004000e <x-coredata://550A4D12-E78C-4D02-9110-EF0CE7BBB8C2/Team/p1>";
    simperiumKey = c7537de8e1794863b9289ca52eec6743;
    })

Everything is saved correctly on Simperium.com. Let me know what more information you need. This is reproducible 10/10.

**This works in v0.7.5**

**Comment by jleandroperez** [comment]
Hello @lukegeiger,

This is the setup we use in the [WordPress iOS App](https://github.com/wordpress-mobile/WordPress-iOS). The *Notification* entity has a couple Transformables, that get translated into NSArray.

Incoming questions below!:
- Just in case: by `Logging Back` you mean, literally, killing the database, entering your credentials, and redownloading everything again, right?.
- Is this entity being sync'ed to other devices? are the transformable attributes being sync'ed there?
- By 'saved correctly on simperium' you mean that the ID's do show up on the dashboard, right?.

If possible, please, try the following:
1. Fresh install + new account
2. Insert a Lineup with the transformables set.
3. Make sure that the change goes through (and please, validate on Simperium.com)
4. Fresh install, again. Log in with verboseLogging enabled.

(Please, grab those logs, it'd be super helpful). Are the Transformables showing up in that initial fresh-install sync?.

Thanks!

**Comment by jleandroperez** [comment]
@lukegeiger may i ask you if you've been able to retrieve the logs?. 

Thank you!

**Comment by lukegeiger** [comment]
@jleandroperez my fault for late response on this... I haven't been able to get the logs again. It seemed to only be happening to me on that day which is weird. I could have messed up and been on an old pod without realizing it. If I see it again I will get the logs and make sure to re open this.

**Comment by jleandroperez** [comment]
@lukegeiger no worries at all!. Thanks for the feedback sir, closing for now then. (If needed) please feel free to reopen.

Have a great day!
