### ISSUE TITLE
Auto-login

### ISSUE THREAD

**Issue by dsmurfin** [Simperium/simperium-ios#521]
It would be great if there was a way to automatically login to Simperium. I'd like to handle all of the login information myself to track other information and then pre-fill the Simperium login. Is there any way to intercept or does this need to be added?

**Comment by jleandroperez** [comment]
Hello there @dsmurfin,

Simperium's [authentication viewController](https://github.com/Simperium/simperium-ios/blob/develop/Simperium/SPAuthenticationViewController.m) exposes all of the UITextField instances (Username / Password).

On top of that, backend auth interaction [is encapsulated within SPAuthenticator](https://github.com/Simperium/simperium-ios/blob/develop/Simperium/SPAuthenticator.h).

You can just subclass SPAuthenticationViewController, and update as needed. All you'd need to do is to make sure you set [the right authenticatorClass here](https://github.com/Simperium/simperium-ios/blob/develop/Simperium/Simperium.h#L216).

For even greater flexibility, you could move the Auth calls to your own backend, and [rely on this helper method](https://github.com/Simperium/simperium-ios/blob/develop/Simperium/Simperium.h#L89) to authenticate Simperium with a given token.

Hope that helps!

**Comment by dsmurfin** [comment]
That's a big help thanks. I'm actually looking at both iOS and OS X, so
I'll look at the window controller as well. There doesn't seem to be so
much flexibility on OS X however.

Thanks again.

____________
Daniel Murfin
t: 07739 022 864
e: dan@dsmurfin.co.uk
w: www.dsmurfin.co.uk / www.danielmurfin.co.uk

**Comment by jleandroperez** [comment]
Glad to help @dsmurfin! Please, let us know if there's anything we could help you with, in the OS X side.

Best,
Jorge
