### ISSUE TITLE
Allow Users To Filter Notes Without Tags

### ISSUE THREAD

**Issue by dcoleonline** [Simperium/simperium-ios#529]
Currently, it's easy to find notes that are tagged, however it isn't possible to find "untagged" notes.

A user reported that they can find untagged notes in the web app by searching “tag:untagged”, but it isn't possible to do the same on any of the apps.

Reported: https://help.automattic.com/staff/index.php?_m=tickets&_a=viewticket&ticketid=2403989

**Comment by fredrocious** [comment]
@dcoleonline I think you were looking for Automattic/simplenote-ios repo, this is for the syncing client library
