### ISSUE TITLE
Nil NSDate field bug

### ISSUE THREAD

**Issue by larryryu** [Simperium/simperium-ios#549]
Ran into an issue where date fields with nil values would eventually generate a diff for a change from 0 to nil. Even though nothing hand changed. Traced it down to this method (in SPMemberDate)
```
 - (id)dateValueFromNumber:(id)value
```
returning 0 if the number is nil

This occurs a lot when simperium fetches all data upon login.

see PR: https://github.com/Simperium/simperium-ios/pull/548 for suggested fix.

**Comment by jleandroperez** [comment]
Closed via #548

Thank you @larryryu!!
