### ISSUE TITLE
Error: Simperium's Pinned Certificate has Expired!

### ISSUE THREAD

**Issue by mmilen** [Simperium/simperium-ios#557]
Hi,

On Mac OS 10.11 I started getting this error recently ; 
37545: CFNetwork internal error (0xc01a:/BuildRoot/Library/Caches/com.apple.xbs/Sources/CFNetwork/CFNetwork-760.6.3/Foundation/NSURLProtocol.mm:182)
2016-09-07 15:45:45.446 SharkBridge[37545:8876255] Error: Simperium's Pinned Certificate has Expired!
2016-09-07 15:45:45.447 SharkBridge[37545:8876109] SocketRocket: In debug mode.  Allowing connection to any root cert

**Comment by jleandroperez** [comment]
Hello @mmilen!

Thanks for the report!. We've addressed this issue [in 0.8.17](https://github.com/Simperium/simperium-ios/releases/tag/v0.8.17).

Nevertheless, there is a [kill switch](https://github.com/Simperium/simperium-ios/blob/v0.8.16/Simperium/SPWebSocketInterface.m#L211) that should be kicking in. Please, debug and verify what's going on in that if statement.

Please, feel free to reopen if needed, thanks!

**Comment by prvnl** [comment]
Hi @jleandroperez!

I'm experiencing the same issue, even when using the 0.8.17 release. All works well but the debugger shows `Error: Simperium's Pinned Certificate has Expired!` Could you please double check this?

Thanks Patrick

**Comment by jleandroperez** [comment]
hello there @prvnl!

The `Error: Simperium's Pinned Certificate has Expired!` is a failsafe we had in place, and was being printed [in this spot](https://github.com/Simperium/simperium-ios/blob/v0.8.16/Simperium/SPWebSocketInterface.m#L234).

This was removed in Mark 0.8.17 (the string itself is nowhere to be found!). Please, double check, it's highly likely you're running with an old lib checkout.

Thanks!

**Comment by prvnl** [comment]
Thanks @jleandroperez, your right! For some reason during compiling the original compiled 0.8.12 framework was being used. Xcode did not compile the new framework version 0.8.17, looks like it has something to do with the change to umbrella headers.

Anyway this issue is solved in 0.8.17!

Thanks!

**Comment by prvnl** [comment]
The reason why I was not seeing the changes, was because I was still linking to the framework `libSimperium.a`, this should now be `Simperium.framework`. Btw, this change is not yet updated in the README.md and documentation.

Maybe this will help others updating from an older version.

**Comment by jleandroperez** [comment]
Ahhhh gotcha, thanks for checking @prvnl!. `README.md` updated, apologies about that, we've been using (internally) Simperium via CocoaPods for quite some time now.

Glad to hear it's sorted out!
