### ISSUE TITLE
Library not getting included

### ISSUE THREAD

**Issue by Himanibathla** [Simperium/simperium-ios#559]
Hi,

I am facing a problem in adding the libraries. I am not able to add libSimperium.a
Please guide @jleandroperez  what can be done to add the library.

**Comment by jleandroperez** [comment]
Hello there,

The docs are a bit outdated. Instead, please, add `Simperium.framework`, we've switched from static libs to Frameworks a while ago. As an alternative (way easier!), you could try adding the library via Cocoapods, should be a one line thing.

**Comment by johnlim5847** [comment]
@jleandroperez may I know what is the cocoapod name? i try pod "simperium-ios" and pod "simperium" both are not working

**Comment by jleandroperez** [comment]
@johnlim5847 please, try with just `Simperium` ([as seen here](https://github.com/Automattic/simplenote-ios/blob/develop/Podfile#L30)).

macOS counterpart [should look like this](https://github.com/Automattic/simplenote-macos/blob/develop/Podfile#L12).

Hope that helps!
