### ISSUE TITLE
dyld: Library not loaded: @rpath/Simperium.framework/Simperium

### ISSUE THREAD

**Issue by katche70** [Simperium/simperium-ios#563]
After update to new version i get following error: 
dyld: Library not loaded: @rpath/Simperium.framework/Simperium

What can i do?

**Comment by jleandroperez** [comment]
Hello there @katche70,

Please, make sure to add **Simperium.framework** to your project's **Build Phases** > **Embed Frameworks** .

Alternatively, you can just add the dependency via Cocoapods, and the rest should be set up automatically for you.

If you're still having any issues, please, feel free to reopen this issue.

Best,
Jorge
