### ISSUE TITLE
Token invalid - 401

### ISSUE THREAD

**Issue by prvnl** [Simperium/simperium-ios#564]
Hi @jleandroperez,

Every once in a while I’m presented the Simperium login view controller. This is the result from the log:

`2017-02-15 09:39:40.412005 AppName[7732:3826600] Simperium found an existing auth token for p****@p**.nl`
`2017-02-15 09:39:40.412052 AppName[7732:3826600] Simperium starting network managers...`
`2017-02-15 09:39:41.350537 AppName[7732:3826626] Simperium received unexpected auth response: {"msg": "Token invalid", "code": 401}`

Is there a token lifespan or something, that could result in this issue? Is there a way to make sure the token stays valid?

Thanks,

Patrick

**Comment by hyling** [comment]
Yes there is a token lifespan.  You can set from your app dashboard at simperium.com under "Manage Keys".

**Comment by prvnl** [comment]
Thanks @hyling ! Good to know about the token lifespan, I should have known this before..

Regards Patrick

**Comment by jleandroperez** [comment]
@prvnl that would be accurate, token life span can be set via the simperium.com dashboard.

Thank you both @hyling + @prvnl!!

**Comment by hyling** [comment]
@prvnl no worries, didn't realize tokens had a lifespan either until I ran across that error message!
