### ISSUE TITLE
Simperium fails to load when embedded within a project

### ISSUE THREAD

**Issue by hyling** [Simperium/simperium-ios#565]
Building with Xcode 8.2.1 this was working in Simperium 0.8.12 but fails in 0.8.18

Steps to reproduce:
Build and RUN samples/Simpletodo/SimpletodoFinal.xcodeproj

I get this error at runtime:
`dyld: Library not loaded: @rpath/Simperium.framework/Simperium`
  `Referenced from: <Path to app that embeds Simperium>`
  `Reason: image not found`

**Comment by hyling** [comment]
I've found a solution!  The problem is the project was changed to build a framework instead of a static library.

The solution is to add the Simperium framework to the "Embedded Binaries" section here: Project Settings > General > Embedded Binaries

I would also recommend including this in step 3 of this page:  https://simperium.com/docs/ios/

**Comment by jleandroperez** [comment]
Addressed via #566. Thanks for helping us out @hyling!
