### ISSUE TITLE
Two small build errors in DiffMatchPatchCFUtilities.c ('check_string' and 'check' functions) in Xcode 9.0 beta 4 (9M189t)

### ISSUE THREAD

**Issue by taskcruncher** [Simperium/simperium-ios#569]
![screenshot_353](https://user-images.githubusercontent.com/765564/28752948-e1286f1c-74f8-11e7-80ef-93344f251507.jpg)

![screenshot_354](https://user-images.githubusercontent.com/765564/28753033-e74c0bfe-74fa-11e7-8231-578c9027280b.jpg)

No errors thrown in build process in beta 2 with same codebase. I'm using (latest) Simperium -- 0.8.18. I understand that Xcode 9 is still beta software: just a heads up.

**Comment by jleandroperez** [comment]
Fixed via #570.

Thank you sir!
