### ISSUE TITLE
Main thread deadlock

### ISSUE THREAD

**Issue by michaelmff** [Simperium/simperium-ios#571]
NSUserDefaults-synchronize is deprecated and should not be used anymore. In SPBucket-setLastChangeSignature: it's called and has created deadlock on the main thread before. Please update your library so this doesn't happen.

**Comment by jleandroperez** [comment]
Hello there @michaelmff,

NSUserDefaults *will* be deprecated in iOS 12, but it's [still valid](https://developer.apple.com/documentation/foundation/userdefaults/1414005-synchronize).

Plus: the deprecation compiler warnings only show up if the **Deployment Target** iOS Version aims at a version in which the method is actually deprecated. Anything below is good. Meaning: it should be safe to leave as is, for now, and until the compiler actually brings that up.

Regarding your deadlock, would it be possible to attach extra details?

- Stack Trace of all of the active threads
- Repro Steps
- And a sample project would be terrific.

Thanks in advance!

**Comment by jleandroperez** [comment]
Closing for now. Feel free to reopen with extra details / repro steps (or!) sample code.

Thanks!
