### ISSUE TITLE
Simperium error ([EntityName]), received an invalid change for (...) {json}

### ISSUE THREAD

**Issue by fvvliet** [Simperium/simperium-ios#58]
Hello simperium-users,

I receive this error when using Simperium in the following situation:
- I downloaded the latest version from github
- use it in iOS project with CoreData
- datamodel contains Category, Note (of type SPManagedObject) and SPManagedObject entities
- 1-to-many relation exists between Category and Note
- testing on 2 iOS devices: create record on one and delete this record on other device.
  This same error is repeated until I quit the app.

Anyone suggestions how to fix this ?

Thanks for advice & suggestions
Frank

**Comment by mmilen** [comment]
Every once in a while I will get this error. Deal is a simple table of straight forward objects. Any idea what I should be checking to find the cause. Most often it happens when my app is installed for the first time. 


```javascript
Simperium error (Deal), received an invalid change for (84257335ea1a49a7883864a22da38eae): {
    ccids =     (
        90f314971a2144af85bc2f6658050bf8
    );
    clientid = "ios-443f7449ac1340beaf7d0c1d96b8bc7e";
    cv = 55aed34c4806f92b41dbb4ab;
    ev = 2;
    id = 84257335ea1a49a7883864a22da38eae;
    o = "-";
}
```

**Comment by jleandroperez** [comment]
@mmilen the error you've posted may be triggered by any of the following scenarios:

A. `Remove OP is received (sent by another peer) while the object was already deleted`
B. `Remove OP was sent, and its confirmation gets received. But the client already logged out + in again`

None of them (should) cause any kind of trouble. Still, it'd be great if the whole log trace could be captured (specially if there are multiple clients involved).

Thanks!

**Comment by mmilen** [comment]
It is scenario A. When a newly installed Mac OS App is connected to 
Simperium servers for the first time , is there a way to force sync it? 
Often it takes a while before the data from server is dumped to the App. 
This does not happen with iOS Apps.


*Milen Milkovski*
CEO / Lead Developer
L'Atelier D'Ema
milen@emabridge.com

**Comment by jleandroperez** [comment]
@mmilen Sorry, i missed a small detail in Scenario (A).

`A. Remove OP is received (sent by another peer) while the object was already LOCALLY deleted`

In which case, it's safe to ignore the log, since it's actually a warning. DB integrity should not have been compromised.

Regarding the "Force Sync", the library is expected to automatically retrieve everything, as soon as you perform the authentication call. We don't really expose anything that would 'Force Sync', since it shouldn't be required at all.

You can learn more about the [Simperium Protocol Here](https://github.com/Simperium/simperium-protocol).

May i ask you how many entities are you currently sync'ing?. Please, try [enabling Verbose Logging](https://github.com/Simperium/simperium-ios/blob/develop/Simperium/Simperium.h#L158), and check the console logs, right after first install + Auth.

**Comment by mmilen** [comment]
Currently regular users have 1-3 devices. I have one test account that 
is running on 5 devices/computers. The App account is SharkBridge, it 
has 3100 total users, 855 active in the last 30 days.

Will I gain anything if I upgrade before I reach the 2000 active users 
threshold.


*Milen Milkovski*
CEO / Lead Developer
L'Atelier D'Ema
milen@emabridge.com

**Comment by jleandroperez** [comment]
Sorry @mmilen, what i meant to say is: how many object instances are you currently sync'ing? (on the account that lags before it downloads it all).

Incoming objects should be processed in batch, and it may take a while if you're dealing with over 10k+ instances.

**Comment by mmilen** [comment]
I have 5 tables with 10-50 objects in each.


*Milen Milkovski*
CEO / Lead Developer
L'Atelier D'Ema
milen@emabridge.com

**Comment by jleandroperez** [comment]
@mmilen ~250 entities shouldn't represent any kind of trouble. Please, check the `Verbose Logs` as soon as you launch the app.

If you're still having any trouble, feel free to open a new issue, we'd be happy to take a look at it.
Make sure to include:

- OSX Version
- Simperium Version
- Snippets being used to initialize the lib (do not include your private keys!)
- Capture of the Verbose logs

Thanks!
